apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::730335375020:role/modena-dev-eks-node-role
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::730335375020:role/modena-dev-jenkins-role
      username: jenkins
      groups:
        - system:masters
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
