# ═══════════════════════════════════════════════════════════════════════════════
# variables.tf - DEV Environment Configuration
# ═══════════════════════════════════════════════════════════════════════════════
# All environment-specific values live HERE, not hardcoded in main.tf
# To change dev settings, edit THIS file only.
# ═══════════════════════════════════════════════════════════════════════════════

# ─────────────────────────────────────────────────────────────────────────────────
# GENERAL
# ─────────────────────────────────────────────────────────────────────────────────
variable "environment" {
  description = "Environment name (dev, stage, prod)"
  type        = string
  default     = "dev"
}

variable "aws_region" {
  description = "AWS region to deploy resources"
  type        = string
  default     = "us-east-1"
}

variable "project_name" {
  description = "Project name used in resource naming"
  type        = string
  default     = "modena"
}

variable "aws_account_id" {
  description = "AWS account ID (12-digit number)"
  type        = string
  default     = "730335375020"  # Your Modena account
}

# ─────────────────────────────────────────────────────────────────────────────────
# VPC CONFIGURATION
# ─────────────────────────────────────────────────────────────────────────────────
variable "vpc_cidr" {
  description = "CIDR block for the VPC"
  type        = string
  default     = "10.0.0.0/16"  # 65,536 IPs
}

variable "enable_nat_gateway" {
  description = "Enable NAT Gateway (costs ~$32/month). Disable for dev to save money."
  type        = bool
  default     = false  # DEV: disabled to save costs
}

# ─────────────────────────────────────────────────────────────────────────────────
# FUTURE: ECR CONFIGURATION (uncomment when we build ECR module)
# ─────────────────────────────────────────────────────────────────────────────────
 variable "ecr_image_retention_count" {
   description = "Number of images to retain in ECR"
   type        = number
   default     = 5  # DEV: keep fewer images
 }
 variable "ecr_scan_on_push" {
  description = "Scan images for vulnerabilities"
  type        = bool
  default     = true
}

# ─────────────────────────────────────────────────────────────────────────────────
# FUTURE: EKS CONFIGURATION (uncomment when we build EKS module)
# ─────────────────────────────────────────────────────────────────────────────────
# variable "eks_node_instance_type" {
#   description = "EC2 instance type for EKS worker nodes"
#   type        = string
#   default     = "t3.small"  # DEV: small instances
# }
#
# variable "eks_node_count" {
#   description = "Number of EKS worker nodes"
#   type        = number
#   default     = 1  # DEV: single node
# }
# ═══════════════════════════════════════════════════════════════════════════════
# EKS VARIABLES
# ═══════════════════════════════════════════════════════════════════════════════

variable "eks_node_disk_size" {
  description = "EKS node disk size in GB"
  type        = number
  default     = 20
}

variable "eks_cluster_version" {
  description = "Kubernetes version"
  type        = string
  default     = "1.29"
}

variable "eks_node_instance_types" {
  description = "EC2 instance types for EKS nodes"
  type        = list(string)
  default     = ["t3.medium"]
}

variable "eks_node_desired_size" {
  description = "Desired number of EKS nodes"
  type        = number
  default     = 1
}

variable "eks_node_min_size" {
  description = "Minimum number of EKS nodes"
  type        = number
  default     = 1
}

variable "eks_node_max_size" {
  description = "Maximum number of EKS nodes"
  type        = number
  default     = 3
}

# ═══════════════════════════════════════════════════════════════════════════════
# RDS VARIABLES
# ═══════════════════════════════════════════════════════════════════════════════

variable "db_password" {
  description = "Master password for RDS (pass via -var or TF_VAR_db_password)"
  type        = string
  sensitive   = true
  default     = ""  # Will be generated by Secrets module
}

variable "rds_master_username" {
  description = "RDS master username"
  type        = string
  default     = "modena_admin"
  sensitive   = true
}

variable "rds_database_name" {
  description = "RDS database name"
  type        = string
  default     = "modena_db"
}

variable "backup_bucket_name" {
  description = "S3 bucket name for backup copies of secrets"
  type        = string
  default     = "modena-secrets-backup-730335375020"
}

variable "rds_instance_class" {
  description = "RDS instance type"
  type        = string
  default     = "db.t3.micro"  # ~$12/month - good for dev
}

variable "rds_allocated_storage" {
  description = "RDS storage in GB"
  type        = number
  default     = 20  # Minimum for gp3
}

variable "rds_multi_az" {
  description = "Enable Multi-AZ for RDS" #"Enable Multi-AZ for RDS (high availability)"
  type        = bool
  default     = false  # DEV: single AZ to save costs
}

# ─────────────────────────────────────────────────────────────────────────────
# JENKINS VARIABLES
# ─────────────────────────────────────────────────────────────────────────────

variable "jenkins_allowed_cidrs" {
  description = "CIDR blocks allowed to access Jenkins (your IP)"
  type        = list(string)
}

variable "key_name" {
  description = "EC2 Key Pair name for SSH access"
  type        = string
}